apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-webpage-config
  namespace: public
data:
  CONFIG_JS: |
    var config = (() => {
      return {
        API: "http://api.emoralesc.kubelabs.tk/graphql",
        WEBSOCKET: "ws://websocket.emoralesc.kubelabs.tk/graphql",
      };
    })();
